### ISSUE TITLE
No calendar button on export

### ISSUE THREAD

**Issue by ArmainAP** [ArmainAP/CashCache#2]

**Comment by jocago** [comment]
I just tried to load the project for the first time and got this error:
"Unable to load addon script from path: 'res://addons/calendar_button/calendar_button.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/calendar_button/plugin.cfg' to prevent further errors."

**Comment by ArmainAP** [comment]
This is related. You can manually enable the plugin and still works in the editor. 
I used an calendar addon I am currently working on creating a completely new one. This will also fix the first time error.

**Comment by ArmainAP** [comment]
Fixed in 0.3.0!
